### ISSUE TITLE
Can't add OpenID

### ISSUE THREAD

**Issue by kaffeeringe** [zikula-modules/OpenID#15]
When I try to add an OpenID to my existing account (index.php?module=openid&type=user&func=newOpenID), I get this error:

Fatal error: Class OpenID_Controller_Authentication contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (Zikula_Controller_AbstractAuthentication::validateAuthenticationInformation) in /htdocs/XXX/modules/OpenID/lib/OpenID/Controller/Authentication.php on line 19

**Comment by cmfcmf** [comment]
Works now.
