### ISSUE TITLE
Issues with new dev release of openid

### ISSUE THREAD

**Issue by rojblake** [zikula-modules/OpenID#16]
Just testing the new 1.3.5 compatible release and this doesn't seem to work for me. 

1) in admin/modifyconfig there are no providers listed for either login or registration
2) Clicking on the openid users link results in the error unknown column openid_type. See stack trace below. I've confirmed this field doesn't exist in my database but is referenced by the doctrine data model

Unknown column openid_type
Exception Trace
#0 Exception thrown in C:\Users\ku04935\Downloads\xampp-portable-lite-win32-1.8.1-VC9\xampp\htdocs\Zikula\core\src\modules\OpenID\lib\OpenID\Controller\Admin.php, line 39.
#1 C:\Users\ku04935\Downloads\xampp-portable-lite-win32-1.8.1-VC9\xampp\htdocs\Zikula\core\src\lib\util\ModUtil.php(1091): call_user_func(Array, Array)
#2 C:\Users\ku04935\Downloads\xampp-portable-lite-win32-1.8.1-VC9\xampp\htdocs\Zikula\core\src\lib\util\ModUtil.php(1173): ModUtil::exec('OpenID', 'admin', 'view', Array, false, NULL)
#3 C:\Users\ku04935\Downloads\xampp-portable-lite-win32-1.8.1-VC9\xampp\htdocs\Zikula\core\src\index.php(78): ModUtil::func('OpenID', 'admin', 'view', Array)
#4 {main}

3) Probably as a result of the above if the default local users session is left to expire then openid break the entire site. 

-Mark

**Comment by cmfcmf** [comment]
Could  you please try again using the latest version? I forgot to push my latest changes…
https://github.com/zikula-modules/OpenID/releases/download/v1.0.0-rc1/OpenID.zip

**Comment by cmfcmf** [comment]
> Probably as a result of the above if the default local users session is left to expire then openid break the entire site.

Sorry for breaking your site :sweat_smile:

**Comment by rojblake** [comment]
it was only broke as long as openid was active. That's what a db editing tool is for. Deactivate the openid module via the status field and back to normal.....

Anyway those new files have got the module running but you said that the local zikula user should be created when the new user successfully authenticates? If so then that doesn't seem to be the case. e.g.  attempting to login via google on demo.markwest.me.uk I get the following 

"Sorry! The information you provided was incorrect. Please check the log-in service you selected and the id you entered, and make sure they match the information associated with your account on this site." 

This is after going to google, signing in and confirming that i'm happy to trust my demo site.

On a side note the "any open id option" says "Unable to contact the OpenID server to start the authorization process." Does this require some configuration as the other provider classes configure an endpoint constant - this one doesn't.

Thanks for all your help in getting this running.

-Mark

**Comment by ghost** [comment]
Needing to have an existing account seems like a big flaw to me. I saw on
the likes of stack exchange and many other site, you can just log-in with a
Google account and it will detect you are not an existing user and offer to
register you using that account. It makes it really simple for the user...
I would a PR  to the core what would allow that to happen.

**Comment by cmfcmf** [comment]
> it was only broke as long as openid was active. That's what a db editing tool is for. Deactivate the openid module via the status field and back to normal.....
> 
> Anyway those new files have got the module running but you said that the local zikula user should be created when the new user successfully authenticates? If so then that doesn't seem to be the case. e.g. attempting to login via google on demo.markwest.me.uk I get the following
> 
> "Sorry! The information you provided was incorrect. Please check the log-in service you selected and the id you entered, and make sure they match the information associated with your account on this site."
> 
> This is after going to google, signing in and confirming that i'm happy to trust my demo site.

Actually, the user is not created if you **login** via google. Click **Create new Account** and choose google there. Then enter your email and username (notice that you don't have to enter a password) and click register. Then it _should_ work. I tested it on your site, but it did not work for me. Did you fix the core bug mentioned in the [README.md](https://github.com/zikula-modules/OpenID/blob/master/README.md)?

> On a side note the "any open id option" says "Unable to contact the OpenID server to start the authorization process." Does this require some configuration as the other provider classes configure an endpoint constant - this one doesn't.

This is the right behaviour. You have to enter something like `me.my-custom-open-id-server.com`. Then this server will be connected and validate your openid.

**Comment by cmfcmf** [comment]
> Needing to have an existing account seems like a big flaw to me. I saw on the likes of stack exchange and many other site, you can just log-in with a Google account and it will detect you are not an existing user and offer to register you using that account. It makes it really simple for the user... I would a PR to the core what would allow that to happen.

This is (almost) possible already. You can register new accounts with your OpenId but you still have to set your email and username. Of course if these were auto-set, this would be a further improvement. Just make sure to click Create new Account and not login.

**Comment by ghost** [comment]
doesnt have to be autoset, just recognise, you are not a user and offer you
to register (enter desired username) and email address.

**Comment by cmfcmf** [comment]
I'll check how this is possible. refs #1 (which is a bit outdated but mentions the same problem)

**Comment by rojblake** [comment]
Your spot-on I didn't make those registration changes. I was focused on how I thought the module should work not on how it actually works. This was in part as I was focused on the requirements for my AD auth module. My thinking was very much like Drak's in that the user logs in using their OpenID credentials gets an account if they don't have one. So in my thought process there was no registration hence I didn't make those changes,.....

Anyway unrelated to this issue i'd very much like to see ZK handle auth modules where the local is automatically created and/or prompted for. For a corporate auth module you don't need the "do you want an account" prompt and you certainly don't want to expose the "create a new account" system. All you need the local account created without the user knowing about it. This is how i'm coding the AD auth module anyway. While this breaks the design of the current auth system it's a case of needs must.

I think this effectively closes this issue anyway and i'll open a FR issue on the main core project to extend the auth architecture to include this logic.

-Mark

**Comment by cmfcmf** [comment]
> I think this effectively closes this issue anyway and i'll open a FR issue on the main core project to extend the auth architecture to include this logic.

Great! Thank you. I will implement this for OpenID after you added it to the core.

**Comment by robbrandt** [comment]
My usage of OpenID is similar to Mark's using AD.  His comments leave open the question of human (as opposed to account) identification on the site.  Certainly an account needs to be created in the background and attached to the OpenID for Zikula to work; the question is how this user is publicly identified on the web pages for people to see.  You could set the username to be the "user" portion of an OpenID (i.e. "rbrandt" for rbrandt.botany.org) but that leaves open to possibility of accidental duplication, where there might also be an rbrandt.zikula.org using the site.  You could set it to be "rbrandtbotanyorg" or some variation, but that's not clean and readable, and for some situations the user might not want their OpenID to be obvious.

In the end, you COULD make it completely automatic based on some formula but I don't think that's the best solution.  A prompt to enter a "screen name" (to use an ancient term) to be used as the unique username is probably the best bet, and conveys to the user that the purpose of the name is to identify himself to others on screen.

**Comment by ghost** [comment]
Better would be to autogenerate a RECOMMENDATION and allow the user to edit it before submit.
