### ISSUE TITLE
remove blobs

### ISSUE THREAD

**Issue by craigh** [zikula-modules/OpenID#20]
you must remove the blob fields from this project. Blobs are not supported in Doctrine 2 and they will cause all DoctrineHelper methods to fail in all modules in the installation and is not supported in ZIkula 1.3

https://github.com/zikula/core/blob/1.3/src/docs/en/dev/upgrading_for_developers.rst#longblob-support

@cmfcmf

**Comment by cmfcmf** [comment]
Refs #17.

Then I won't publish this before refactoring to Doctrine2.

**Comment by ghost** [comment]
I think you still MUST transform the field types in MySQL itself. This is because Doctrine schema too reverse engineers the database schema. So you need to do an ALTER on the actual DB table fields.

**Comment by cmfcmf** [comment]
@drak As OpenID was never published I can simply reinstall and do not have to think about updating.

**Comment by ghost** [comment]
ah i see, yes :)
