### ISSUE TITLE
"Any OpenID" not working

### ISSUE THREAD

**Issue by robbrandt** [zikula-modules/OpenID#23]
Hi, we are attempting to integrate this into our Zikula 1.3.5 site.  I have applied all of the changes in the readme.md.  As a test, I have logins working with the Google option, so I believe I have a functioning module.

We want to use this with our own OpenID server, but I am unable to connect my OpenID to my account in Zikula.  When I enter my ID in the Add an OpenID page, I am correctly delivered to our OpenID server, but when I log it doesn't refer me back to Zikula.

Ideas?  I can create a test account for you on our OpenID server if you want to test it against one of your own installations.  The site we are working on isn't live yet for you to try it there.

**Comment by cmfcmf** [comment]
I can try to figure out what's going wrong, a test account might help. Can you try to insert `https://www.google.com/accounts/o8/id` as `Any OpenID` and see if it works?

**Comment by robbrandt** [comment]
Thanks for the fast response.  Yes, that seems to work although my google id is already in there, so it wasn't able to do the whole thing.  It said it was already associated.

I just tried Any OpenID trying to use a wordpress.com identity (since myopenid and myid.net seem to have gone offline) and I get similar results as for our server.  So I don't think it's our server per se.  We are running a server that's using an older protocol version of OpenID.  We plan to upgrade it to another server soon, but that's not there yet.

So rather than creating a test account, try using a wordpress.com ID.  You just have to create an account and create a free blog, and you will have an ID there.

**Comment by robbrandt** [comment]
I will have a patch for this, I have it working locally.

What is the functional status of this module?  It seems to have been refactored and abandoned in a non-functional state?

**Comment by cmfcmf** [comment]
Sounds great!

I'm not exactly sure about the status of the module. Before I started refactoring it, it didn't work because it was using a `blob` database type and had several other issues. Currently I don't have much time, but I think I can have another look at this module in the next weeks.

**Comment by robbrandt** [comment]
In what context does it not work?  I have the module working great in Zikula 1.3.7.

I will have a snippet for you to include on Monday.  This resolution is simple.  The v1 OpenID spec does not require openid_ns, but your implementation does.  So v1 spec providers that do not pass openid_ns fail.  About 5 lines of code in the proper location...

**Comment by robbrandt** [comment]
OpenID v1.x spec issue:

lib/OpenID/Api/Authentication, line 330:
Change

---

``` php
$openidNamespace = $this->request->query->get('openid_ns', null);
$openidConsumer = @new Auth_OpenID_Consumer(new OpenID_PHPOpenID_OpenIDStore(), new OpenID_PHPOpenID_SessionStore());

 if (!isset($openidNamespace) || empty($openidNamespace)) {
```

---

to

---

``` php
$openidNamespace = $this->request->query->get('openid_ns', null);
        $openidConsumer = @new Auth_OpenID_Consumer(new OpenID_PHPOpenID_OpenIDStore(), new OpenID_PHPOpenID_SessionStore());

        // support optional and missing openid_ns in some v1 spec implementations
        $openidMode = $this->request->query->get('openid_mode', null);
        if ((is_null($openidNamespace) || $openidNamespace == 'null') && $openidMode == "id_res"){
            // looks like a v1 spec without openid.ns set.  Set it to the v1 optional value
            $openidNamespace = "http://openid.net/signon/1.1";
        }

        if (!isset($openidNamespace) || empty($openidNamespace)) {
```

---

**Comment by cmfcmf** [comment]
> In what context does it not work? I have the module working great in Zikula 1.3.7.

Sorry for the confusion, the module is working :smile:
