### ISSUE TITLE
Deleting the OpenID module with users whose only authentication method is OpenID will prevent users from logging in.

### ISSUE THREAD

**Issue by rmburkhead** [zikula-modules/OpenID#3]
== Describe the defect ==

Users who register with an OpenID do not get a Users account password. If their OpenID is their only authentication method, then deleting the module will prevent the user from ever being able to log in.

== What released version, CI build number, or development version? ==

[a497a6ff0b675a97bdc459568fa9c203626d33f9]

**Comment by cmfcmf** [comment]
Closed by 9d53cd4.

If a user tries to uninstall the module and there are users with no password set, the uninstallation will be denied with this error message:
- The user "USERNAME" would not be able to login anymore if you uninstall this module.
- If you really want to uninstall this module, you have two possibilities: Either delete the users via the Users module or set random passwords for them via the OpenID admin interface.

It is possible to set random passwords for the users via the OpenID admin interface.
